services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:1337@db:5432/rust_db?sslmode=disable
    ports:
      - "443:443"
    depends_on:
      - db


  db:
    container_name: db
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1337
      - POSTGRES_DB=rust_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  graphana:
    image: grafana/grafana-oss
    container_name: grafana
    user: "0"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - db