[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
serde = "^1.0"
serde_json = "^1.0"
opencv = "0.94.4"
toml = "^0.8"


[[bin]]
name = "server"
path = "src/main.rs" 