[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
prost = "0.13.5"
prost-types = "0.13.5"
postgres = "0.19.10"

[build-dependencies]
prost-build = "0.13.5"

[[bin]]
name = "client"
path = "src/main.rs"